// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas_common::inventory_entry {
    use infinite_seas_common::item_id_quantity_pair::ItemIdQuantityPair;

    const EDataTooLong: u64 = 102;

    struct InventoryEntry has store, drop, copy {
        item_id_and_quantity: ItemIdQuantityPair,
        sign: u8,
    }

    public fun new(
        item_id_and_quantity: ItemIdQuantityPair,
        sign: u8,
    ): InventoryEntry {
        let inventory_entry = InventoryEntry {
            item_id_and_quantity,
            sign,
        };
        validate(&inventory_entry);
        inventory_entry
    }

    fun validate(inventory_entry: &InventoryEntry) {
        let _ = inventory_entry;
    }

    public fun item_id_and_quantity(inventory_entry: &InventoryEntry): ItemIdQuantityPair {
        inventory_entry.item_id_and_quantity
    }

    public fun sign(inventory_entry: &InventoryEntry): u8 {
        inventory_entry.sign
    }

}
