// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas_common::skill_process_id {
    const EDataTooLong: u64 = 102;
    const EInvalidEnumValue: u64 = 106;

    struct SkillProcessId has store, drop, copy {
        skill_type: u8,
        player_id: address,
        sequence_number: u8,
    }

    public fun new(
        skill_type: u8,
        player_id: address,
        sequence_number: u8,
    ): SkillProcessId {
        let skill_process_id = SkillProcessId {
            skill_type,
            player_id,
            sequence_number,
        };
        validate(&skill_process_id);
        skill_process_id
    }

    fun validate(skill_process_id: &SkillProcessId) {
        assert!(infinite_seas_common::skill_type::is_valid(skill_process_id.skill_type), EInvalidEnumValue);
    }

    public fun skill_type(skill_process_id: &SkillProcessId): u8 {
        skill_process_id.skill_type
    }

    public fun player_id(skill_process_id: &SkillProcessId): address {
        skill_process_id.player_id
    }

    public fun sequence_number(skill_process_id: &SkillProcessId): u8 {
        skill_process_id.sequence_number
    }

}
