// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas_map::map_friend_config {
    use std::signer;
    use std::string::String;
    use std::vector;
    use aptos_std::type_info;

    const ENotInitialized: u64 = 100;
    const ENotAllowedCaller: u64 = 101;
    const ENotPublisher: u64 = 102;
    //const ENotAdmin: u64 = 103;

    struct MapFriendConfig has key, store {
        caller_allowlist: vector<String>,
    }

    fun init_module(account: &signer) { // Or //? public entry fun initialize(account: &signer) {
        assert!(std::signer::address_of(account) == @infinite_seas_map, ENotPublisher); // NOTE: Is this ok?
        let config = MapFriendConfig {
            caller_allowlist: vector::empty(),
        };
        move_to(account, config);
    }

    public fun add_allowed_caller<WT: drop>(account: &signer) acquires MapFriendConfig {
        assert!(std::signer::address_of(account) == @infinite_seas_map, ENotPublisher); // NOTE: Is this ok?
        let config = borrow_global_mut<MapFriendConfig>(signer::address_of(account));
        let type_name = type_info::type_name<WT>();
        if (!vector::contains(&config.caller_allowlist, &type_name)) {
            vector::push_back(&mut config.caller_allowlist, type_name);
        };
    }

    public fun remove_allowed_caller<WT: drop>(account: &signer) acquires MapFriendConfig {
        assert!(std::signer::address_of(account) == @infinite_seas_map, ENotPublisher); // NOTE: Is this ok?
        let config = borrow_global_mut<MapFriendConfig>(signer::address_of(account));
        let type_name = type_info::type_name<WT>();
        vector::remove_value(&mut config.caller_allowlist, &type_name);
    }

    public fun assert_allowlisted<WT: drop>(_friend_witness: WT) acquires MapFriendConfig {
        assert!(exists<MapFriendConfig>(@infinite_seas_map), ENotInitialized);
        let config = borrow_global<MapFriendConfig>(@infinite_seas_map);
        assert!(vector::contains(&config.caller_allowlist, &type_info::type_name<WT>()), ENotAllowedCaller);
    }
}
