[package]
name = "InfiniteSeasCommon"
version = "0.0.1"

[addresses]
infinite_seas_common = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
