// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas_player::infinite_seas_player_init {
    use infinite_seas_player::player;

    public entry fun initialize(store_account: &signer) {
        player::initialize(store_account);
    }

}
