// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas::ship_battle {
    use aptos_framework::account;
    use aptos_framework::event;
    use aptos_framework::object;
    use infinite_seas::genesis_account;
    use infinite_seas::pass_object;
    use std::option::{Self, Option};
    friend infinite_seas::ship_battle_aggregate;

    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const ENotInitialized: u64 = 110;

    struct Events has key {
    }

    public fun initialize(account: &signer) {
        genesis_account::assert_genesis_account(account);

        let res_account = genesis_account::resource_account_signer();
        move_to(&res_account, Events {
        });

    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct ShipBattle has key {
        version: u64,
        initiator: address,
        responder: address,
        status: u8,
        initiator_experiences: vector<u32>,
        responder_experiences: vector<u32>,
        ended_at: Option<u64>,
        winner: Option<u8>,
        round_number: u32,
        round_started_at: u64,
        round_mover: Option<u8>,
        round_attacker_ship: Option<address>,
        round_defender_ship: Option<address>,
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct ObjectController has key {
        extend_ref: object::ExtendRef,
        delete_ref: object::DeleteRef,
        transfer_ref: object::TransferRef,
    }


    public(friend) fun save_object_controller(
        object_signer: &signer,
        extend_ref: object::ExtendRef,
        delete_ref: object::DeleteRef,
        transfer_ref: object::TransferRef,
    ) {
        move_to(
            object_signer,
            ObjectController {
                extend_ref,
                delete_ref,
                transfer_ref
            }
        )
    }

    public fun version(ship_battle: &ShipBattle): u64 {
        ship_battle.version
    }

    public fun initiator(ship_battle: &ShipBattle): address {
        ship_battle.initiator
    }

    public(friend) fun set_initiator(ship_battle: &mut ShipBattle, initiator: address) {
        ship_battle.initiator = initiator;
    }

    public fun responder(ship_battle: &ShipBattle): address {
        ship_battle.responder
    }

    public(friend) fun set_responder(ship_battle: &mut ShipBattle, responder: address) {
        ship_battle.responder = responder;
    }

    public fun status(ship_battle: &ShipBattle): u8 {
        ship_battle.status
    }

    public(friend) fun set_status(ship_battle: &mut ShipBattle, status: u8) {
        ship_battle.status = status;
    }

    public fun borrow_initiator_experiences(ship_battle: &ShipBattle): &vector<u32> {
        &ship_battle.initiator_experiences
    }

    public(friend) fun borrow_mut_initiator_experiences(ship_battle: &mut ShipBattle): &mut vector<u32> {
        &mut ship_battle.initiator_experiences
    }

    public fun initiator_experiences(ship_battle: &ShipBattle): vector<u32> {
        ship_battle.initiator_experiences
    }

    public(friend) fun set_initiator_experiences(ship_battle: &mut ShipBattle, initiator_experiences: vector<u32>) {
        ship_battle.initiator_experiences = initiator_experiences;
    }

    public fun borrow_responder_experiences(ship_battle: &ShipBattle): &vector<u32> {
        &ship_battle.responder_experiences
    }

    public(friend) fun borrow_mut_responder_experiences(ship_battle: &mut ShipBattle): &mut vector<u32> {
        &mut ship_battle.responder_experiences
    }

    public fun responder_experiences(ship_battle: &ShipBattle): vector<u32> {
        ship_battle.responder_experiences
    }

    public(friend) fun set_responder_experiences(ship_battle: &mut ShipBattle, responder_experiences: vector<u32>) {
        ship_battle.responder_experiences = responder_experiences;
    }

    public fun ended_at(ship_battle: &ShipBattle): Option<u64> {
        ship_battle.ended_at
    }

    public(friend) fun set_ended_at(ship_battle: &mut ShipBattle, ended_at: Option<u64>) {
        ship_battle.ended_at = ended_at;
    }

    public fun winner(ship_battle: &ShipBattle): Option<u8> {
        ship_battle.winner
    }

    public(friend) fun set_winner(ship_battle: &mut ShipBattle, winner: Option<u8>) {
        ship_battle.winner = winner;
    }

    public fun round_number(ship_battle: &ShipBattle): u32 {
        ship_battle.round_number
    }

    public(friend) fun set_round_number(ship_battle: &mut ShipBattle, round_number: u32) {
        ship_battle.round_number = round_number;
    }

    public fun round_started_at(ship_battle: &ShipBattle): u64 {
        ship_battle.round_started_at
    }

    public(friend) fun set_round_started_at(ship_battle: &mut ShipBattle, round_started_at: u64) {
        ship_battle.round_started_at = round_started_at;
    }

    public fun round_mover(ship_battle: &ShipBattle): Option<u8> {
        ship_battle.round_mover
    }

    public(friend) fun set_round_mover(ship_battle: &mut ShipBattle, round_mover: Option<u8>) {
        ship_battle.round_mover = round_mover;
    }

    public fun round_attacker_ship(ship_battle: &ShipBattle): Option<address> {
        ship_battle.round_attacker_ship
    }

    public(friend) fun set_round_attacker_ship(ship_battle: &mut ShipBattle, round_attacker_ship: Option<address>) {
        ship_battle.round_attacker_ship = round_attacker_ship;
    }

    public fun round_defender_ship(ship_battle: &ShipBattle): Option<address> {
        ship_battle.round_defender_ship
    }

    public(friend) fun set_round_defender_ship(ship_battle: &mut ShipBattle, round_defender_ship: Option<address>) {
        ship_battle.round_defender_ship = round_defender_ship;
    }

    public(friend) fun new_ship_battle(
        initiator: address,
        responder: address,
        status: u8,
        round_started_at: u64,
        round_mover: Option<u8>,
        round_attacker_ship: Option<address>,
        round_defender_ship: Option<address>,
    ): ShipBattle {
        ShipBattle {
            version: 0,
            initiator,
            responder,
            status,
            initiator_experiences: std::vector::empty(),
            responder_experiences: std::vector::empty(),
            ended_at: std::option::none(),
            winner: std::option::none(),
            round_number: 1,
            round_started_at,
            round_mover,
            round_attacker_ship,
            round_defender_ship,
        }
    }


    public(friend) fun update_version_and_add(obj_addr: address, ship_battle: ShipBattle) acquires ObjectController {
        ship_battle.version = ship_battle.version + 1;
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        let object_signer = object::generate_signer_for_extending(extend_ref);
        private_add_ship_battle(&object_signer, ship_battle)
    }

    public(friend) fun add_ship_battle(object_signer: &signer, ship_battle: ShipBattle) {
        assert!(ship_battle.version == 0, EInappropriateVersion);
        private_add_ship_battle(object_signer, ship_battle);
    }

    public(friend) fun remove_ship_battle(obj_addr: address): ShipBattle acquires ShipBattle {
        move_from<ShipBattle>(obj_addr)
    }

    fun private_add_ship_battle(object_signer: &signer, ship_battle: ShipBattle) {
        move_to(object_signer, ship_battle);
    }

    public(friend) fun delete_ship_battle(obj_addr: address) acquires ObjectController {
        let ObjectController {
            extend_ref: _extend_ref,
            delete_ref,
            transfer_ref: _transfer_ref,
        } = move_from<ObjectController>(
            obj_addr
        );
        object::delete(delete_ref)
    }

    public fun get_ship_battle(obj_addr: address): pass_object::PassObject<ShipBattle> acquires ShipBattle {
        let ship_battle = remove_ship_battle(obj_addr);
        pass_object::new_with_address(ship_battle, obj_addr)
    }

    public fun return_ship_battle(ship_battle_pass_obj: pass_object::PassObject<ShipBattle>) acquires ObjectController {
        let (ship_battle, obj_addr) = pass_object::extract_value_and_address(ship_battle_pass_obj);
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        let object_signer = object::generate_signer_for_extending(extend_ref);
        private_add_ship_battle(&object_signer, ship_battle);
    }

    public(friend) fun drop_ship_battle(ship_battle: ShipBattle) {
        let ShipBattle {
            version: _version,
            initiator: _initiator,
            responder: _responder,
            status: _status,
            initiator_experiences: _initiator_experiences,
            responder_experiences: _responder_experiences,
            ended_at: _ended_at,
            winner: _winner,
            round_number: _round_number,
            round_started_at: _round_started_at,
            round_mover: _round_mover,
            round_attacker_ship: _round_attacker_ship,
            round_defender_ship: _round_defender_ship,
        } = ship_battle;
    }

}
