// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas::ship_battle_aggregate {
    use aptos_framework::object::{Self, Object};
    use infinite_seas::ship_battle::{Self, ShipBattle};
    use std::signer;

}
