// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas::skill_process {
    use aptos_framework::account;
    use aptos_framework::event;
    use aptos_framework::object;
    use infinite_seas::genesis_account;
    use infinite_seas::pass_object;
    use infinite_seas_common::item_id_quantity_pairs::ItemIdQuantityPairs;
    use infinite_seas_common::skill_process_id::SkillProcessId;
    use std::option::{Self, Option};
    friend infinite_seas::skill_process_create_logic;
    friend infinite_seas::skill_process_aggregate;

    const EDataTooLong: u64 = 102;
    const EInappropriateVersion: u64 = 103;
    const ENotInitialized: u64 = 110;

    struct Events has key {
        skill_process_created_handle: event::EventHandle<SkillProcessCreated>,
    }

    public fun initialize(account: &signer) {
        genesis_account::assert_genesis_account(account);

        let res_account = genesis_account::resource_account_signer();
        move_to(&res_account, Events {
            skill_process_created_handle: account::new_event_handle<SkillProcessCreated>(&res_account),
        });

    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct SkillProcess has key {
        version: u64,
        skill_process_id: SkillProcessId,
        item_id: u32,
        started_at: u64,
        creation_time: u64,
        completed: bool,
        ended_at: u64,
        production_materials: Option<ItemIdQuantityPairs>,
        batch_size: u32,
    }

    #[resource_group_member(group = aptos_framework::object::ObjectGroup)]
    struct ObjectController has key {
        extend_ref: object::ExtendRef,
        transfer_ref: object::TransferRef,
    }


    public(friend) fun save_object_controller(
        object_signer: &signer,
        extend_ref: object::ExtendRef,
        transfer_ref: object::TransferRef,
    ) {
        move_to(
            object_signer,
            ObjectController {
                extend_ref,
                transfer_ref
            }
        )
    }

    public fun version(skill_process: &SkillProcess): u64 {
        skill_process.version
    }

    public fun skill_process_id(skill_process: &SkillProcess): SkillProcessId {
        skill_process.skill_process_id
    }

    public(friend) fun set_skill_process_id(skill_process: &mut SkillProcess, skill_process_id: SkillProcessId) {
        skill_process.skill_process_id = skill_process_id;
    }

    public fun item_id(skill_process: &SkillProcess): u32 {
        skill_process.item_id
    }

    public(friend) fun set_item_id(skill_process: &mut SkillProcess, item_id: u32) {
        skill_process.item_id = item_id;
    }

    public fun started_at(skill_process: &SkillProcess): u64 {
        skill_process.started_at
    }

    public(friend) fun set_started_at(skill_process: &mut SkillProcess, started_at: u64) {
        skill_process.started_at = started_at;
    }

    public fun creation_time(skill_process: &SkillProcess): u64 {
        skill_process.creation_time
    }

    public(friend) fun set_creation_time(skill_process: &mut SkillProcess, creation_time: u64) {
        skill_process.creation_time = creation_time;
    }

    public fun completed(skill_process: &SkillProcess): bool {
        skill_process.completed
    }

    public(friend) fun set_completed(skill_process: &mut SkillProcess, completed: bool) {
        skill_process.completed = completed;
    }

    public fun ended_at(skill_process: &SkillProcess): u64 {
        skill_process.ended_at
    }

    public(friend) fun set_ended_at(skill_process: &mut SkillProcess, ended_at: u64) {
        skill_process.ended_at = ended_at;
    }

    public fun production_materials(skill_process: &SkillProcess): Option<ItemIdQuantityPairs> {
        skill_process.production_materials
    }

    public(friend) fun set_production_materials(skill_process: &mut SkillProcess, production_materials: Option<ItemIdQuantityPairs>) {
        skill_process.production_materials = production_materials;
    }

    public fun batch_size(skill_process: &SkillProcess): u32 {
        skill_process.batch_size
    }

    public(friend) fun set_batch_size(skill_process: &mut SkillProcess, batch_size: u32) {
        skill_process.batch_size = batch_size;
    }

    public(friend) fun new_skill_process(
        skill_process_id: SkillProcessId,
    ): SkillProcess {
        SkillProcess {
            version: 0,
            skill_process_id,
            item_id: infinite_seas_common::item_id::unused_item(),
            started_at: 0,
            creation_time: 0,
            completed: true,
            ended_at: 0,
            production_materials: std::option::none(),
            batch_size: 1,
        }
    }

    struct SkillProcessCreated has store, drop {
        id: option::Option<address>,
        skill_process_id: SkillProcessId,
    }

    public fun skill_process_created_id(skill_process_created: &SkillProcessCreated): option::Option<address> {
        skill_process_created.id
    }

    public(friend) fun set_skill_process_created_id(skill_process_created: &mut SkillProcessCreated, id: address) {
        skill_process_created.id = option::some(id);
    }

    public fun skill_process_created_skill_process_id(skill_process_created: &SkillProcessCreated): SkillProcessId {
        skill_process_created.skill_process_id
    }

    public(friend) fun new_skill_process_created(
        skill_process_id: SkillProcessId,
    ): SkillProcessCreated {
        SkillProcessCreated {
            id: option::none(),
            skill_process_id,
        }
    }


    public(friend) fun update_version_and_add(obj_addr: address, skill_process: SkillProcess) acquires ObjectController {
        skill_process.version = skill_process.version + 1;
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        let object_signer = object::generate_signer_for_extending(extend_ref);
        private_add_skill_process(&object_signer, skill_process)
    }

    public(friend) fun add_skill_process(object_signer: &signer, skill_process: SkillProcess) {
        assert!(skill_process.version == 0, EInappropriateVersion);
        private_add_skill_process(object_signer, skill_process);
    }

    public(friend) fun remove_skill_process(obj_addr: address): SkillProcess acquires SkillProcess {
        move_from<SkillProcess>(obj_addr)
    }

    fun private_add_skill_process(object_signer: &signer, skill_process: SkillProcess) {
        move_to(object_signer, skill_process);
    }

    public fun get_skill_process(obj_addr: address): pass_object::PassObject<SkillProcess> acquires SkillProcess {
        let skill_process = remove_skill_process(obj_addr);
        pass_object::new_with_address(skill_process, obj_addr)
    }

    public fun return_skill_process(skill_process_pass_obj: pass_object::PassObject<SkillProcess>) acquires ObjectController {
        let (skill_process, obj_addr) = pass_object::extract_value_and_address(skill_process_pass_obj);
        let extend_ref = &borrow_global<ObjectController>(obj_addr).extend_ref;
        let object_signer = object::generate_signer_for_extending(extend_ref);
        private_add_skill_process(&object_signer, skill_process);
    }

    public(friend) fun drop_skill_process(skill_process: SkillProcess) {
        let SkillProcess {
            version: _version,
            skill_process_id: _skill_process_id,
            item_id: _item_id,
            started_at: _started_at,
            creation_time: _creation_time,
            completed: _completed,
            ended_at: _ended_at,
            production_materials: _production_materials,
            batch_size: _batch_size,
        } = skill_process;
    }

    public(friend) fun emit_skill_process_created(skill_process_created: SkillProcessCreated) acquires Events {
        assert!(exists<Events>(genesis_account::resource_account_address()), ENotInitialized);
        let events = borrow_global_mut<Events>(genesis_account::resource_account_address());
        event::emit_event(&mut events.skill_process_created_handle, skill_process_created);
    }

}
