// <autogenerated>
//   This file was generated by dddappp code generator.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

module infinite_seas_production::infinite_seas_production_init {
    use infinite_seas_production::skill_process;

    public entry fun initialize(store_account: &signer) {
        skill_process::initialize(store_account);
    }

}
